version: '2'
services:

### MySQL ###############################################

  mysql:
    image: mysql:5.7
    container_name: gpas-1.8.0-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./sqls:/docker-entrypoint-initdb.d
    labels:
      - "service-name:gpas"
      - "service-type:db-srv"
      - "environment:test"
      
### WildFly #############################################
  wildfly:
    image: mosaicgreifswald/wildfly
    container_name: gpas-1.8.0-wildfly
    links:
      - "mysql:mysqldb"
    ports:
      - "8080:8080"
      - "9990:9990"
    environment:
      WILDFLY_PASS: wildfly_2018
    depends_on:
      - mysql
    volumes:
      - ./jboss:/entrypoint-jboss-batch
      - ./deployments:/entrypoint-deployments
    labels:
      - "service-name:gpas"
      - "service-type:app-srv"
      - "environment:test"
    entrypoint: /bin/bash
    command: -c "./wait-for-it.sh mysql:3306 -t 120 && ./run.sh"
